version: "3.6"

services:
  centos7:
    image: centos:latest
    container_name: centos7
    command: tail -f /dev/null
  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu
    command: >
      bash -c "
      apt update &&
      apt install -y python3 &&
      tail -f /dev/null"
  fedora:
    image: pycontribs/fedora
    container_name: fedora
    command: tail -f /dev/null
